FORMAT: 1A

# Papageno API
Papageno API is the API to the [Papageno choirs manager](http://www.papageno.info/) available at https://www.papageno.info/api/v1/ or https://staging.papageno.info/api/v1/.
The SSL certificates are available at [/www.papageno.info.cert](http://www.papageno.info/www.papageno.info.cert) and [/staging.papageno.info.cert](http://staging.papageno.info/staging.papageno.info.cert), respectively.

All requests except authorization requests `/oauth/*` require authorization token to be present in the header `Authorization: Bearer <access_token>`.

# Group Authorization
OAuth2 authorization

## Using username and password [/oauth/token]

Only API call that doesn't use /api/v1 prefix

### Authorize [POST]
+ Parameters

    + grant_type  (required, string)  ... Grant type. Has to be `password` in this case.
    + client_id   (required, string)  ... Client id obtainder from the provider (Papageno)
    + username    (required, string)  ... Papageno user's email address
    + password    (required, string)  ... Papageno user's password

+ Request (application/json)

        {
          "grant_type": "password",
          "client_id": "2c98244711dd3d09b7782adbb8d95c83e972eeffd2939dd0f68a3951b6435130",
          "username": "username",
          "password": "user_password"
        }

+ Response 200 (application/json)

        {
          "access_token": "09732c68d78b8119e3fb197a66f79e860f76fa4760fb79fd8271562aad3694b6",
          "token_type": "bearer",
          "expires_in": 7200,
          "refresh_token":"d701cefa5804adb6aefc628eefd0a6730f009f069be973aab2306c6ef888ba53"
        }

# Group Users
## User [/users/{id}]

A single user with its details

### GET

Returns user details or `HTTP 403`

+ Parameters

    + id (required, string, `1`)  ... User's id. Can be `me` in which case it is referencing current user

+ Request (application/json)

    + Headers

        Authorization: Bearer <acces_token>

+ Response 200 (application/json)

    {
      "id": 1,
      "first_name": "First",
      "last_name" : "Last",
      "email"     : "user@example.com",
      "choirs"     : [
            {
              "id": 1,
              "slug": "choir-1",
              "name": "Choir 1"
            }
        ]
    }
